version: "3.8"

services:
  project1:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_URL=jdbc:postgresql://postgresdb-1.cokq2ji1eim5.us-east-1.rds.amazonaws.com:5432/postgres
      - DB_USERNAME=postgresDB
      - DB_PASSWORD=basketball
    container_name: project1-container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=basketball
    container_name: postgres_container
    volumes:
     - db-data:/var/lib/postgresql/data
volumes:
  db-data:
   driver: local
  